### ISSUE TITLE
I like your changes to the theme (image)

### ISSUE THREAD

**Issue by abdiasriver** [Zenithar/zenithar.hugo#1]
Hi¡ zenithar  , i was looking your personal [blog] (https://blog.zenithar.org/)and you use the minimal theme like me,

and i like your changes , if you can share how you do, for the image on the homepage,

and how i do the animation to show the content  :+1: 

thanks @Zenithar

**Comment by Zenithar** [comment]
Hello,

You can find my "minimal" version inlined in the repository.
Maybe, I could extract it as a dedicated repo ^^

Regards,
